---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create
      cisco.meraki.organizations:
        meraki_suppress_logging: true
        # meraki_username: "{{meraki_username}}"
        # meraki_password: "{{meraki_password}}"
        # meraki_verify: "{{meraki_verify}}"
        # meraki_port: "{{meraki_port}}"
        # meraki_version: "{{meraki_version}}"
        # meraki_debug: "{{meraki_debug}}"
        state: present
        management:
          details:
          - name: MSP ID
            value: '1234567'
        name: Test Ansible
        api:
          enabled: True
